---
- hosts: all
  #user: hosts #hosts No es necesario indicar user si el playbook afecta a un grupo
  become: yes
  ignore_errors: true
  environment:
    http_proxy: http://proxy.gfi.es:8000
    https_proxy: http://proxy.gfi.es:8000

  # En la carpeta defaults estan las variables y en las de tasks estan las tareas de ese rol
  # El orden en el que aparecen los roles en este yml sera el orden de ejecucion

  roles:
    - { role: common, tags: common }
    - { role: jenkins, tags: jenkins }
  

