---
- name: instala common_packages
  apt:
   name: "{{ item }}" #variable que toma los valores de with_items
   update_cache: yes
   state: present  #si ponemos absent lo desinstala con latest instala el mas nuevo
  with_items:
   - "{{ common_packages }}" # recorre las variable declaradas en vars en base_packages
  when: ansible_pkg_mgr == 'apt'

# Cambia la linea de permit root login para poner un yes
- name: Permite root ssh login en ubuntu
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: 'PermitRootLogin prohibit-password' 
    line: 'PermitRootLogin yes'       
    state: present
  when: ansible_pkg_mgr == 'apt'