---
- name: instala common_packages
  apt:
   name: "{{ item }}" #variable que toma los valores de with_items
   update_cache: yes
   state: present  #si ponemos absent lo desinstala con latest instala el mas nuevo
  with_items:
   - "{{ common_packages }}" # recorre las variable declaradas en vars en base_packages
  when: ansible_pkg_mgr == 'apt'
