---
- name: Add repo key Jenkins apt
  apt_key:
    url: "{{ jenkins_public_key_url }}"
    state: present
  when: ansible_pkg_mgr == 'apt'
  tags:
    - jenkins

- name: Add repo Jenkins apt
  apt_repository:
   repo: "{{ jenkins_repo_url }}"
   #baseurl: https://pkg.jenkins.io/debian-stable binary/jenkins_2.7.4_all.deb 
   update_cache: yes
   #gpgkey: https://pkg.jenkins.io/debian-stable/jenkins.io.key
  when: ansible_pkg_mgr == 'apt'

- name: instala jenkins
  apt:
   name: "{{ item }}" #variable que toma los valores de with_items
   update_cache: yes
   state: present  #si ponemos absent lo desinstala con latest instala el mas nuevo
  with_items:
   - "{{ jenkins_packages }}" 
  when: ansible_pkg_mgr == 'apt'

- name: inicia servicio jenkins
  service:
   name: jenkins
   state: started
   enabled: yes #lo inicia al arrancar